Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2019-11, with the labels that each got.

#110 Alert Muting Rule Resource
  go.mod
  go.sum
  signalfx/provider.go
  signalfx/resource_signalfx_alert_muting_rule.go
  signalfx/resource_signalfx_alert_muting_rule_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/alertmuting.go
  vendor/github.com/signalfx/signalfx-go/alertmuting/model_alert_muting_rule.go
  vendor/github.com/signalfx/signalfx-go/alertmuting/model_alert_muting_rule_filter.go
  vendor/github.com/signalfx/signalfx-go/alertmuting/model_create_update_alert_muting_rule_request.go
  vendor/github.com/signalfx/signalfx-go/alertmuting/model_search_result.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_create_update_dashboard_group_request.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_dashboard_group.go
  vendor/github.com/signalfx/signalfx-go/detector/model_create_detector_request.go
  vendor/github.com/signalfx/signalfx-go/detector/model_detector.go
  vendor/modules.txt
  website/docs/r/alert_muting_rule.html.markdown
  website/signalfx.erb
Labels: dependencies, documentation, size/XL

#109 Add authorized writer fields to detector, dashboard and dashboard group
  .travis.yml
  CHANGELOG.md
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_dashboard_group.go
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_team.go
  website/docs/r/dashboard_group.html.markdown
  website/docs/r/detector.html.markdown
Labels: dependencies, documentation, size/L

#113 Don't validate subscriptions like services
  signalfx/resource_signalfx_azure_integration.go
Labels: size/XS

#114 [website] Update broken/old URL for SignalFlow docs
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#115 Small doc fixes
  website/docs/r/azure_integration.html.markdown
  website/signalfx.erb
Labels: documentation, size/XS

#117 Small doc addition for detectors
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS
