Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2019-10, with the labels that each got.

#99 List charts complain if color scales are specified without the correct color_by
  CHANGELOG.md
  signalfx/resource_signalfx_list_chart.go
  website/docs/r/list_chart.html.markdown
Labels: documentation, size/S

#100 Fix column width in grid schema
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_dashboard_test.go
Labels: size/S

#102 Adjust behavior of layouts to allow more than one instance.
  CHANGELOG.md
  signalfx/resource_signalfx_dashboard.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/M

#106 Add support for Jira notification
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/notifications.go
  signalfx/notifications_test.go
  signalfx/provider.go
  signalfx/resource_jira_integration.go
  signalfx/resource_jira_integration_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_adfs_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_jira_assignee.go
  vendor/github.com/signalfx/signalfx-go/integration/model_jira_integration.go
  vendor/github.com/signalfx/signalfx-go/jira_integration.go
  vendor/github.com/signalfx/signalfx-go/notification/model_amazoneventbrige_notification.go
  vendor/github.com/signalfx/signalfx-go/notification/model_big_panda_notification.go
  vendor/github.com/signalfx/signalfx-go/notification/model_jira_notification.go
  vendor/github.com/signalfx/signalfx-go/notification/model_notification.go
  vendor/github.com/signalfx/signalfx-go/signalflow/conn.go
  vendor/modules.txt
  website/docs/r/detector.html.markdown
  website/docs/r/jira_integration.html.markdown
  website/signalfx.erb
Labels: dependencies, documentation, size/XL
