Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2019-07, with the labels that each got.

#1 Update package import path
  main.go
Labels: size/XS

#6 Update docs to point to new repo
  README.md
Labels: size/XS

#7 Update module path
  go.mod
Labels: documentation, size/XS

#8 Remove some gone fields from docs
  CHANGELOG.md
  go.mod
  go.sum
  stripe_functionality_test.tf
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/L

#10 Version Formatting Fix
  CHANGELOG.md
Labels: size/XS

#11 Remove temporary doc blurb
  README.md
Labels: size/XS

#18 Time Range Upgrades
  CHANGELOG.md
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_detector_test.go
  signalfx/resource_signalfx_event_feed_chart.go
  signalfx/resource_signalfx_time_chart.go
Labels: size/M

#21 Fix crash with grids
  CHANGELOG.md
  signalfx/resource_signalfx_dashboard.go
Labels: size/XS

#22 Bump sfx-go and adapt to various pointers
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_event_feed_chart.go
  signalfx/resource_signalfx_heatmap_chart.go
  signalfx/resource_signalfx_list_chart.go
  signalfx/resource_signalfx_single_value_chart.go
  signalfx/resource_signalfx_time_chart.go
  signalfx/util.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/chart/model_axes.go
  vendor/github.com/signalfx/signalfx-go/chart/model_event_publish_label_options.go
  vendor/github.com/signalfx/signalfx-go/chart/model_general_options.go
  vendor/github.com/signalfx/signalfx-go/chart/model_histogram_chart_options.go
  vendor/github.com/signalfx/signalfx-go/chart/model_options.go
  vendor/github.com/signalfx/signalfx-go/chart/model_publish_label_options.go
  vendor/github.com/signalfx/signalfx-go/chart/model_secondary_visualization.go
  vendor/github.com/signalfx/signalfx-go/chart/model_time_display_options.go
  vendor/github.com/signalfx/signalfx-go/dashboard/model_chart_event_overlay.go
  vendor/github.com/signalfx/signalfx-go/dashboard/model_create_update_dashboard_request.go
  vendor/github.com/signalfx/signalfx-go/dashboard/model_dashboard.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_clone_dashboard_group_request.go
  vendor/github.com/signalfx/signalfx-go/detector/model_create_detector_request.go
  vendor/github.com/signalfx/signalfx-go/detector/model_detector.go
  vendor/github.com/signalfx/signalfx-go/detector/model_time.go
  vendor/modules.txt
Labels: dependencies, size/XL

#24 Rework some default handling
  signalfx/resource_signalfx_single_value_chart.go
  signalfx/resource_signalfx_time_chart.go
  signalfx/util.go
Labels: size/M

#26 Updated documentation to include credentialId for Slack
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#29 Remove credentialName field from OpsGenie notifications
  CHANGELOG.md
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_detector_test.go
Labels: size/S

#27 Add display name to schema and add import testing
  CHANGELOG.md
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_dashboard_and_friends_test.go
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_detector_test.go
  signalfx/resource_signalfx_event_feed_chart.go
  signalfx/resource_signalfx_event_feed_chart_test.go
  signalfx/resource_signalfx_heatmap_chart.go
  signalfx/resource_signalfx_heatmap_chart_test.go
  signalfx/resource_signalfx_list_chart.go
  signalfx/resource_signalfx_list_chart_test.go
  signalfx/resource_signalfx_single_value_chart.go
  signalfx/resource_signalfx_single_value_chart_test.go
  signalfx/resource_signalfx_text_chart.go
  signalfx/resource_signalfx_text_chart_test.go
  signalfx/resource_signalfx_time_chart.go
  signalfx/resource_signalfx_time_chart_test.go
  website/docs/r/list_chart.html.markdown
  website/docs/r/single_value_chart.html.markdown
  website/docs/r/time_chart.html.markdown
Labels: documentation, size/XL

#31 Add docs for multiple notifications
  CHANGELOG.md
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#32 AWS Integration
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/provider.go
  signalfx/resource_signalfx_integration_aws.go
  signalfx/resource_signalfx_integration_aws_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_adfs_integration_model.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_auth_method.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_cloud_watch_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_custom_name_space_sync_rule.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_name_space_sync_rule.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_service.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_sync_rule_filter.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_sync_rule_filter_action.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_active_directory_integration_model.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_environment.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_integration_model.go
  vendor/github.com/signalfx/signalfx-go/integration/model_big_panda_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_bitium_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_gcp_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_gcp_project.go
  vendor/github.com/signalfx/signalfx-go/integration/model_google_cloud_identity_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_integration_common_properties.go
  vendor/github.com/signalfx/signalfx-go/integration/model_issuer_url.go
  vendor/github.com/signalfx/signalfx-go/integration/model_new_relic_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_new_relic_integration_filter_object.go
  vendor/github.com/signalfx/signalfx-go/integration/model_office365_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_okta_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_one_login_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_opsgenie_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_pager_duty_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_ping_one_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_poll_rate.go
  vendor/github.com/signalfx/signalfx-go/integration/model_service_now_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_slack_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_type.go
  vendor/github.com/signalfx/signalfx-go/integration/model_victor_ops_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_webhook_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_x_matters_integration.go
  vendor/github.com/signalfx/signalfx-go/team/model_opsgenie_notification.go
  vendor/modules.txt
  website/docs/r/integration_aws.html.markdown
  website/docs/r/integration_pagerduty.html.markdown
Labels: dependencies, documentation, size/XXL

#36 Updating docs for Opsgenie notifications.
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#34 Azure resource
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/provider.go
  signalfx/resource_signalfx_integration_aws.go
  signalfx/resource_signalfx_integration_azure.go
  signalfx/resource_signalfx_integration_azure_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/aws_cloudwatch_integration.go
  vendor/github.com/signalfx/signalfx-go/azure_integration.go
  vendor/github.com/signalfx/signalfx-go/integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_service.go
  vendor/modules.txt
Labels: dependencies, size/XL

#37 Add docs for azure and fix some bum links
  CHANGELOG.md
  website/docs/r/integration_azure.html.markdown
  website/docs/r/integration_gcp.html.markdown
  website/docs/r/integration_slack.html.markdown
  website/signalfx.erb
Labels: documentation, size/M

#38 Fix incorrect detection of status codes
  CHANGELOG.md
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_dashboard_group.go
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_integration_aws.go
  signalfx/resource_signalfx_integration_azure.go
  signalfx/util.go
Labels: size/XS

#39 Fix defaults on watermarks
  CHANGELOG.md
  signalfx/resource_signalfx_time_chart.go
Labels: size/XS

#40 Don't allow more than one left or right axis
  CHANGELOG.md
  signalfx/resource_signalfx_time_chart.go
Labels: size/XS

#41 docs: fix syntax for gcp integration example
  website/docs/r/integration_gcp.html.markdown
Labels: documentation, size/XS

#42 docs: gcp integration: improve example for multiple projects
  website/docs/r/integration_gcp.html.markdown
Labels: documentation, size/XS
