Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-05, with the labels that each got.

#200 Version bump of Terraform SDK and add configurable timeout
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/provider.go
  signalfx/resource_signalfx_dashboard_and_friends_test.go
  signalfx/resource_signalfx_data_link.go
  vendor/github.com/hashicorp/go-getter/.travis.yml
  vendor/github.com/hashicorp/go-getter/README.md
  vendor/github.com/hashicorp/go-getter/client.go
  vendor/github.com/hashicorp/go-getter/get_git.go
  vendor/github.com/hashicorp/go-getter/get_http.go
  vendor/github.com/hashicorp/hcl/.travis.yml
  vendor/github.com/hashicorp/hcl/decoder.go
  vendor/github.com/hashicorp/hcl/go.mod
  vendor/github.com/hashicorp/hcl/go.sum
  vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
  vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go
  vendor/github.com/hashicorp/hcl/json/scanner/scanner.go
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/README.md
  vendor/github.com/hashicorp/hcl/v2/appveyor.yml
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/README.md
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/customdecode.go
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/expression_type.go
  vendor/github.com/hashicorp/hcl/v2/ext/typeexpr/README.md
  vendor/github.com/hashicorp/hcl/v2/ext/typeexpr/type_type.go
  vendor/github.com/hashicorp/hcl/v2/go.mod
  vendor/github.com/hashicorp/hcl/v2/go.sum
  vendor/github.com/hashicorp/hcl/v2/gohcl/decode.go
  vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_body.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_expression.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/generate.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load_hcl.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load_legacy.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/module.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/provider_ref.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_config.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go
  vendor/github.com/hashicorp/terraform-plugin-test/helper.go
  vendor/github.com/hashicorp/terraform-plugin-test/util.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, size/XXL

#201 Add size validation for program text
  CHANGELOG.md
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_event_feed_chart.go
  signalfx/resource_signalfx_heatmap_chart.go
  signalfx/resource_signalfx_list_chart.go
  signalfx/resource_signalfx_single_value_chart.go
  signalfx/resource_signalfx_time_chart.go
Labels: size/S

#203 Azure Service Additions
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_service.go
  vendor/modules.txt
Labels: dependencies, size/M

#205 Bump sfx-go to pick up azure service name fixes
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_service.go
  vendor/modules.txt
Labels: dependencies, size/S

#207 Bump sfx-go, improve validation, and add GCP data source
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/data_source_gcp_services.go
  signalfx/resource_signalfx_aws_integration.go
  signalfx/resource_signalfx_aws_integration_test.go
  signalfx/resource_signalfx_azure_integration.go
  signalfx/resource_signalfx_azure_integration_test.go
  signalfx/resource_signalfx_gcp_integration.go
  signalfx/resource_signalfx_gcp_integration_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/chart.go
  vendor/github.com/signalfx/signalfx-go/dashboard.go
  vendor/github.com/signalfx/signalfx-go/dashboardgroup.go
  vendor/github.com/signalfx/signalfx-go/datalink.go
  vendor/github.com/signalfx/signalfx-go/detector.go
  vendor/github.com/signalfx/signalfx-go/integration/model_gcp_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_gcp_service.go
  vendor/github.com/signalfx/signalfx-go/metrics_metadata.go
  vendor/github.com/signalfx/signalfx-go/organization.go
  vendor/github.com/signalfx/signalfx-go/orgtoken.go
  vendor/github.com/signalfx/signalfx-go/signalflow/fake_backend.go
  vendor/github.com/signalfx/signalfx-go/team.go
  vendor/modules.txt
  website/docs/d/gcp_services.markdown
  website/docs/r/aws_integration.html.markdown
  website/docs/r/azure_integration.html.markdown
  website/docs/r/gcp_integration.html.markdown
  website/signalfx.erb
Labels: dependencies, documentation, size/XL

#211 Enable API HTTP requests/responses logging in debug mode
  signalfx/provider.go
Labels: size/XS

#213 Allow provider configuration api_url and custom_app_url to be set from environment variables
  signalfx/provider.go
  signalfx/provider_test.go
  signalfx/resource_signalfx_alert_muting_rule_test.go
  signalfx/resource_signalfx_aws_integration_test.go
  signalfx/resource_signalfx_azure_integration_test.go
  signalfx/resource_signalfx_dashboard_and_friends_test.go
  signalfx/resource_signalfx_data_link_test.go
  signalfx/resource_signalfx_detector_test.go
  signalfx/resource_signalfx_event_feed_chart_test.go
  signalfx/resource_signalfx_gcp_integration_test.go
  signalfx/resource_signalfx_heatmap_chart_test.go
  signalfx/resource_signalfx_jira_integration_test.go
  signalfx/resource_signalfx_list_chart_test.go
  signalfx/resource_signalfx_opsgenie_integration_test.go
  signalfx/resource_signalfx_org_token_test.go
  signalfx/resource_signalfx_pagerduty_integration_test.go
  signalfx/resource_signalfx_single_value_chart_test.go
  signalfx/resource_signalfx_slack_integration_test.go
  signalfx/resource_signalfx_team_test.go
  signalfx/resource_signalfx_text_chart_test.go
  signalfx/resource_signalfx_time_chart_test.go
  signalfx/resource_signalfx_victor_ops_integration_test.go
  signalfx/resource_signalfx_webhook_integration_test.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#212 Add support for GCP Compute Metadata Whitelist
  signalfx/resource_signalfx_gcp_integration.go
  signalfx/resource_signalfx_gcp_integration_test.go
  signalfx/util.go
  website/docs/r/gcp_integration.html.markdown
Labels: documentation, size/S
