Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-02, with the labels that each got.

#154 Fix property name only for data links
  CHANGELOG.md
  signalfx/resource_signalfx_data_link.go
  signalfx/resource_signalfx_data_link_test.go
Labels: size/M

#158 Add webhook resource
  go.mod
  go.sum
  signalfx/provider.go
  signalfx/resource_signalfx_webhook_integration.go
  signalfx/resource_signalfx_webhook_integration_test.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/webhook_integration.go
  vendor/modules.txt
  website/docs/r/webhook_integration.html.markdown
  website/signalfx.erb
Labels: dependencies, documentation, size/XL

#159 #157 fix webhhook typo in documentation
  website/signalfx.erb
Labels: documentation, size/XS
