Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-03, with the labels that each got.

#161 AWS filter changes
  CHANGELOG.md
  signalfx/resource_signalfx_aws_integration.go
  website/docs/r/aws_integration.html.markdown
Labels: documentation, size/S

#163 Bump dep for new AWS services
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_service.go
  vendor/modules.txt
Labels: dependencies, size/S

#166 #165 bunch of improvements on detector documentation
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#167 Version bump for AWS Services
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_service.go
  vendor/modules.txt
Labels: dependencies, size/S

#168 Add discoveryOptions to dashboard
  go.mod
  go.sum
  signalfx/resource_signalfx_dashboard.go
  signalfx/resource_signalfx_dashboard_group.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/dashboard/model_create_update_dashboard_request.go
  vendor/github.com/signalfx/signalfx-go/dashboard/model_dashboard.go
  vendor/github.com/signalfx/signalfx-go/dashboard/model_discovery_options.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_create_update_dashboard_group_request.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_dashboard_group.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_import_filter.go
  vendor/github.com/signalfx/signalfx-go/dashboard_group/model_import_qualifier.go
  vendor/modules.txt
Labels: dependencies, size/L

#170 Fix namespace sync rules with missing filters
  signalfx/resource_signalfx_aws_integration.go
Labels: size/XS

#171 Add a default to max delay, set it all the time
  CHANGELOG.md
  signalfx/resource_signalfx_detector.go
Labels: size/XS

#172 Bump version to get new AWS service name
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_service.go
  vendor/github.com/signalfx/signalfx-go/signalflow/client.go
  vendor/modules.txt
  website/docs/r/aws_integration.html.markdown
Labels: dependencies, documentation, size/S

#173 Bump sfx-go dep
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_service.go
  vendor/modules.txt
Labels: dependencies, size/XL

#174 Use correct types for various chart features
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/resource_signalfx_time_chart.go
  signalfx/util.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/chart/model_axes.go
  vendor/github.com/signalfx/signalfx-go/chart/model_color_scale.go
  vendor/github.com/signalfx/signalfx-go/chart/model_secondary_visualization.go
  vendor/github.com/signalfx/signalfx-go/signalflow/computation.go
  vendor/modules.txt
Labels: dependencies, size/M

#176 Version bump of sfx-go to pick up data link fixes
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/datalink/model_target.go
  vendor/github.com/signalfx/signalfx-go/detector.go
  vendor/github.com/signalfx/signalfx-go/signalflow/computation.go
  vendor/github.com/signalfx/signalfx-go/signalflow/messages/info.go
  vendor/modules.txt
Labels: dependencies, size/M

#177 Add Dial, TLS, and total connection timeouts.
  signalfx/provider.go
Labels: size/XS

#180 Fix unclean plans when using AWS services
  CHANGELOG.md
  signalfx/resource_signalfx_aws_integration.go
Labels: size/M

#183 Respect standard environment variables for HTTP proxies
  signalfx/provider.go
Labels: size/XS
