Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-04, with the labels that each got.

#185 Fix spelling error in docs for signalfx_team resource
  website/docs/r/team.html.markdown
Labels: documentation, size/XS

#186 Update heatmap_chart.html.markdown
  website/docs/r/heatmap_chart.html.markdown
Labels: documentation, size/XS

#187 Update list_chart.html.markdown
  website/docs/r/list_chart.html.markdown
Labels: documentation, size/XS

#188 Add dimension values data source
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/data_source_dimension_values.go
  signalfx/provider.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/chart.go
  vendor/github.com/signalfx/signalfx-go/metrics_metadata.go
  vendor/modules.txt
  website/docs/d/dimension_values.markdown
  website/signalfx.erb
Labels: dependencies, documentation, size/L

#189 Require services and have at least 1 item
  CHANGELOG.md
  signalfx/resource_signalfx_azure_integration.go
Labels: size/XS

#192 Don't try and set null limits on org tokens
  CHANGELOG.md
  signalfx/resource_signalfx_org_token.go
Labels: size/XS

#194 Add secret to org tokens
  CHANGELOG.md
  signalfx/resource_signalfx_org_token.go
Labels: size/XS

#196 Handle automatic heatmap color range
  CHANGELOG.md
  signalfx/resource_signalfx_heatmap_chart.go
  website/docs/r/heatmap_chart.html.markdown
Labels: documentation, size/XS

#198 Improve HTTP safety
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/provider.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/alertmuting.go
  vendor/github.com/signalfx/signalfx-go/aws_cloudwatch_integration.go
  vendor/github.com/signalfx/signalfx-go/azure_integration.go
  vendor/github.com/signalfx/signalfx-go/chart.go
  vendor/github.com/signalfx/signalfx-go/dashboard.go
  vendor/github.com/signalfx/signalfx-go/dashboardgroup.go
  vendor/github.com/signalfx/signalfx-go/datalink.go
  vendor/github.com/signalfx/signalfx-go/detector.go
  vendor/github.com/signalfx/signalfx-go/gcp_integration.go
  vendor/github.com/signalfx/signalfx-go/integration.go
  vendor/github.com/signalfx/signalfx-go/jira_integration.go
  vendor/github.com/signalfx/signalfx-go/metrics_metadata.go
  vendor/github.com/signalfx/signalfx-go/opsgenie_integration.go
  vendor/github.com/signalfx/signalfx-go/organization.go
  vendor/github.com/signalfx/signalfx-go/orgtoken.go
  vendor/github.com/signalfx/signalfx-go/pagerduty_integration.go
  vendor/github.com/signalfx/signalfx-go/sessiontoken.go
  vendor/github.com/signalfx/signalfx-go/slack_integration.go
  vendor/github.com/signalfx/signalfx-go/team.go
  vendor/github.com/signalfx/signalfx-go/victor_ops_integration.go
  vendor/github.com/signalfx/signalfx-go/webhook_integration.go
  vendor/modules.txt
Labels: dependencies, size/XL
