Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-06, with the labels that each got.

#214 Bump sfx-go and use namedToken
  go.mod
  go.sum
  signalfx/resource_signalfx_aws_external_integration.go
  signalfx/resource_signalfx_aws_integration.go
  signalfx/resource_signalfx_aws_token_integration.go
  signalfx/resource_signalfx_azure_integration.go
  signalfx/resource_signalfx_gcp_integration.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_cloud_watch_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_azure_integration.go
  vendor/github.com/signalfx/signalfx-go/integration/model_gcp_integration.go
  vendor/modules.txt
Labels: dependencies, size/M

#217 Format terraform documentation samples with terrafmt
  website/docs/d/aws_services.markdown
  website/docs/d/azure_services.markdown
  website/docs/d/dimension_values.markdown
  website/docs/d/gcp_services.markdown
  website/docs/r/alert_muting_rule.html.markdown
  website/docs/r/aws_external_integration.html.markdown
  website/docs/r/aws_integration.html.markdown
  website/docs/r/aws_token_integration.html.markdown
  website/docs/r/azure_integration.html.markdown
  website/docs/r/dashboard.html.markdown
  website/docs/r/dashboard_group.html.markdown
  website/docs/r/data_link.html.markdown
  website/docs/r/detector.html.markdown
  website/docs/r/event_feed_chart.html.markdown
  website/docs/r/gcp_integration.html.markdown
  website/docs/r/heatmap_chart.html.markdown
  website/docs/r/jira_integration.html.markdown
  website/docs/r/list_chart.html.markdown
  website/docs/r/opsgenie_integration.html.markdown
  website/docs/r/org_token.html.markdown
  website/docs/r/pagerduty_integration.html.markdown
  website/docs/r/single_value_chart.html.markdown
  website/docs/r/slack_integration.html.markdown
  website/docs/r/team.html.markdown
  website/docs/r/text_chart.html.markdown
  website/docs/r/time_chart.html.markdown
  website/docs/r/victor_ops_integration.html.markdown
  website/docs/r/webhook_integration.html.markdown
Labels: documentation, size/XL

#221 Adjust user agent
  CHANGELOG.md
  signalfx/provider.go
Labels: size/XS
