Repository splunk-terraform/terraform-provider-signalfx, pull requests merged in 2020-01, with the labels that each got.

#134 Doc `description` field in a signalfx detector
  website/docs/r/detector.html.markdown
Labels: documentation, size/XS

#136 Validate color by and handle case
  CHANGELOG.md
  signalfx/resource_signalfx_single_value_chart.go
Labels: size/XS

#137 Add time bits to list chart
  signalfx/resource_signalfx_list_chart.go
  website/docs/r/list_chart.html.markdown
Labels: documentation, size/M

#138 More color by validation
  CHANGELOG.md
  signalfx/resource_signalfx_list_chart.go
  signalfx/resource_signalfx_time_chart.go
Labels: size/XS

#139 Validate unit_prefix
  CHANGELOG.md
  signalfx/resource_signalfx_heatmap_chart.go
  signalfx/resource_signalfx_list_chart.go
  signalfx/resource_signalfx_single_value_chart.go
  signalfx/resource_signalfx_time_chart.go
Labels: size/XS

#140 Bump dep and add AWS account ARN response
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/resource_signalfx_aws_external_integration.go
  signalfx/resource_signalfx_aws_token_integration.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/client.go
  vendor/github.com/signalfx/signalfx-go/integration/model_aws_cloud_watch_integration.go
  vendor/github.com/signalfx/signalfx-go/sessiontoken.go
  vendor/github.com/signalfx/signalfx-go/sessiontoken/model_create_token_request.go
  vendor/github.com/signalfx/signalfx-go/sessiontoken/model_token.go
  vendor/modules.txt
  website/docs/r/aws_external_integration.html.markdown
  website/docs/r/aws_token_integration.html.markdown
Labels: dependencies, documentation, size/L

#141 Add Detector viz options
  CHANGELOG.md
  go.mod
  go.sum
  signalfx/resource_signalfx_detector.go
  signalfx/resource_signalfx_detector_test.go
  signalfx/resource_signalfx_org_token.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/float.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/int.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/network.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/time.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/uuid.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/validation.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/resource_provider.go
  vendor/github.com/signalfx/signalfx-go/CHANGELOG.md
  vendor/github.com/signalfx/signalfx-go/detector/model_publish_label_options.go
  vendor/github.com/signalfx/signalfx-go/detector/model_visualization.go
  vendor/modules.txt
  website/docs/r/detector.html.markdown
Labels: dependencies, documentation, size/XXL

#143 Validate on_chart_legend_dimension and use helpers for convenience
  signalfx/resource_signalfx_time_chart.go
  signalfx/resource_signalfx_time_chart_test.go
Labels: size/M

#145 Change validation of on chart legend options
  CHANGELOG.md
  signalfx/resource_signalfx_time_chart.go
Labels: size/XS
